# Generated by Django 4.2.5 on 2023-09-19 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('developer', models.CharField(max_length=255)),
                ('genre', models.CharField(max_length=255)),
                ('price', models.IntegerField(default='')),
                ('amount', models.IntegerField(default='')),
                ('description', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
